name: Deploy Salt Master

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  salt-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Apply Salt State
        uses: appleboy/ssh-action@master
        with:
          host: 34.88.12.192
          script: |
            cd /srv/saltstack && git pull && salt '*' state.apply state_output=minimal state_verbose=False && salt '*' saltutil.refresh_pillar && salt '*' saltutil.sync_modules && salt '*' saltutil.sync_grains
